In [1]:
import pydataset

In [3]:
tips = pydataset.data('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
1       16.99  1.01  Female     No  Sun  Dinner     2
2       10.34  1.66    Male     No  Sun  Dinner     3
3       21.01  3.50    Male     No  Sun  Dinner     3
4       23.68  3.31    Male     No  Sun  Dinner     2
5       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
tips = tips.rename(columns={'size': 'party_size'})

In [11]:
# if is a reserved word in python
if = 3

SyntaxError: invalid syntax (<ipython-input-11-914aca9a0590>, line 2)

In [9]:
# .max is a method, a function that lives on the dataframe
tips.max()
# .size and .shape are properties
tips.size
tips.shape

total_bill             50.81
tip                       10
sex                     Male
smoker                   Yes
day                     Thur
time                   Lunch
party_size                 6
tip_percentage      0.710345
price_per_person      20.275
dtype: object

In [7]:
tips['tip_percentage'] = tips.tip / tips.total_bill
tips['price_per_person'] = tips.total_bill / tips.party_size

In [12]:
tips.head()

,total_bill,tip,sex,smoker,day,time,party_size,tip_percentage,price_per_person
1,16.99,1.01,Female,No,Sun,Dinner,2,0.059447,8.495000
2,10.34,1.66,Male,No,Sun,Dinner,3,0.160542,3.446667
3,21.01,3.50,Male,No,Sun,Dinner,3,0.166587,7.003333
4,23.68,3.31,Male,No,Sun,Dinner,2,0.139780,11.840000
5,24.59,3.61,Female,No,Sun,Dinner,4,0.146808,6.147500

In [16]:
import sklearn.linear_model
import sklearn.feature_selection

k = 2

# initialize the sklearn objects
lm = sklearn.linear_model.LinearRegression()
kbest = sklearn.feature_selection.SelectKBest(sklearn.feature_selection.f_regression, 2)
rfe = sklearn.feature_selection.RFE(lm, 2)

In [20]:
# prep our data
import sklearn.model_selection

train, test = sklearn.model_selection.train_test_split(tips, random_state=123, train_size=.80)

x_cols = ['total_bill', 'party_size', 'tip_percentage', 'price_per_person']
X_train = train[x_cols]
y_train = train.tip

X_test = test[x_cols]
y_test = test.tip

How to use scikit-learn objects:

1. Make the thing
2. Fit the thing (`.fit`) on the training data
3. Use the thing (`.tranform`, `.predict`) on the training data or the test data, or even unseen data

In [24]:
kbest.fit(X_train, y_train)
X_train.columns[kbest.get_support()]

Index(['total_bill', 'party_size'], dtype='object')

In [30]:
rfe.fit(X_train, y_train)
X_train.columns[rfe.support_]

Index(['total_bill', 'tip_percentage'], dtype='object')

In [40]:
rfe.support_

array([ True, False,  True, False])

In [43]:
X_train.columns[rfe.support_]

Index(['total_bill', 'tip_percentage'], dtype='object')

In [27]:
# exploring what .transform does
X_train
X_train_kbest_features = kbest.transform(X_train)

In [31]:
def select_kbest(X, y, k):
    kbest = sklearn.feature_selection.SelectKBest(sklearn.feature_selection.f_regression, k)
    kbest.fit(X, y)
    return X.columns[kbest.get_support()]

In [32]:
select_kbest(X_train, y_train, 2)

Index(['total_bill', 'party_size'], dtype='object')

In [44]:
def select_rfe(X, y, k):
    lm = sklearn.linear_model.LinearRegression()
    rfe = sklearn.feature_selection.RFE(lm, k)
    rfe.fit(X, y)
    return X.columns[rfe.support_]

In [45]:
select_rfe(X_train, y_train, 2)

Index(['total_bill', 'tip_percentage'], dtype='object')

In [47]:
swiss = pydataset.data('swiss')
swiss

,Fertility,Agriculture,Examination,Education,Catholic,Infant.Mortality
Courtelary,80.2,17.0,15,12,9.96,22.2
Delemont,83.1,45.1,6,9,84.84,22.2
Franches-Mnt,92.5,39.7,5,5,93.40,20.2
Moutier,85.8,36.5,12,7,33.77,20.3
Neuveville,76.9,43.5,17,15,5.16,20.6
Porrentruy,76.1,35.3,9,7,90.57,26.6
Broye,83.8,70.2,16,7,92.85,23.6
Glane,92.4,67.8,14,8,97.16,24.9
Gruyere,82.4,53.3,12,7,97.67,21.0
Sarine,82.9,45.2,16,13,91.38,24.4
Veveyse,87.1,64.5,14,6,98.61,24.5
Aigle,64.1,62.0,21,12,8.52,16.5
Aubonne,66.9,67.5,14,7,2.27,19.1
Avenches,68.9,60.7,19,12,4.43,22.7
Cossonay,61.7,69.3,22,5,2.82,18.7
Echallens,68.3,72.6,18,2,24.20,21.2
Grandson,71.7,34.0,17,8,3.30,20.0
Lausanne,55.7,19.4,26,28,12.11,20.2
La Vallee,54.3,15.2,31,20,2.15,10.8
Lavaux,65.1,73.0,19,9,2.84,20.0
Morges,65.5,59.8,22,10,5.23,18.0
Moudon,65.0,55.1,14,3,4.52,22.4
Nyone,56.6,50.9,22,12,15.14,16.7
Orbe,57.4,54.1,20,6,4.20,15.3
Oron,72.5,71.2,12,1,2.40,21.0
Payerne,74.2,58.1,14,8,5.23,23.8
Paysd'enhaut,72.0,63.5,6,3,2.56,18.0
Rolle,60.5,60.8,16,10,7.72,16.3
Vevey,58.3,26.8,25,19,18.46,20.9
Yverdon,65.4,49.5,15,8,6.10,22.5
Conthey,75.5,85.9,3,2,99.71,15.1
Entremont,69.3,84.9,7,6,99.68,19.8
Herens,77.3,89.7,5,2,100.00,18.3
Martigwy,70.5,78.2,12,6,98.96,19.4
Monthey,79.4,64.9,7,3,98.22,20.2
St Maurice,65.0,75.9,9,9,99.06,17.8
Sierre,92.2,84.6,3,3,99.46,16.3
Sion,79.3,63.1,13,13,96.83,18.1
Boudry,70.4,38.4,26,12,5.62,20.3
La Chauxdfnd,65.7,7.7,29,11,13.79,20.5
Le Locle,72.7,16.7,22,13,11.22,18.9
Neuchatel,64.4,17.6,35,32,16.92,23.0
Val de Ruz,77.6,37.6,15,7,4.97,20.0
ValdeTravers,67.6,18.7,25,7,8.65,19.5
V. De Geneve,35.0,1.2,37,53,42.34,18.0
Rive Droite,44.7,46.6,16,29,50.43,18.2
Rive Gauche,42.8,27.7,22,29,58.33,19.3

In [53]:
train, test = sklearn.model_selection.train_test_split(swiss, random_state=123, train_size=.8)

X_train = train.drop(columns='Fertility')
y_train = train.Fertility

X_test = test.drop(columns='Fertility')
y_test = test.Fertility

In [54]:
select_kbest(X_train, y_train, 3)

Index(['Examination', 'Education', 'Catholic'], dtype='object')

In [55]:
select_rfe(X_train, y_train, 3)

Index(['Examination', 'Education', 'Infant.Mortality'], dtype='object')

In [58]:
lm.fit(X_train, y_train)

lm.coef_

array([-0.21156852, -0.39409426, -0.92225189,  0.12007924,  1.68540012])